import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container">
          <header className="header">
            <Navbar />
          </header>

          <main>{children}</main>

          <footer className="footer">
            <div>© {new Date().getFullYear()} Saniya Akbar</div>
            <div>Contact: <a href="mailto:saniyaakbarofficial@gmail.com">saniyaakbarofficial@gmail.com</a></div>
          </footer>
        </div>
      </body>
    </html>
  );
}
